---
- hosts: default
  sudo: yes

  tasks:
    - name: stable source list
      copy: src=files/sources.list/stable dest=/etc/apt/sources.list

    - name: Installing apt-transport-https
      apt: pkg=apt-transport-https state=present

    - name: add fpcomplete key
      apt_key: url=https://s3.amazonaws.com/download.fpcomplete.com/debian/fpco.key state=present

    - name: add hhvm key
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=0x5a16e7281be7a449 state=present

    - name: varnish key
      apt_key: url=https://repo.varnish-cache.org/GPG-key.txt

    - name: add stack repo
      apt_repository: repo='deb http://download.fpcomplete.com/debian/jessie stable main' state=present

    - name: add hhvm repo
      apt_repository: repo='deb http://dl.hhvm.com/debian jessie main' state=present

    - name: add varnish repo
      apt_repository: repo='deb https://repo.varnish-cache.org/debian/ jessie varnish-4.1' state=present

    - name: Installing packages
      apt: pkg={{item}} update_cache=yes state=latest
      with_items:
        - hhvm
        - varnish
        - nginx
        - postgresql
        - emacs
        - mg
        - git
        - stack
