---
- hosts: default
  sudo: yes

  tasks:
    - name: stable source list
      copy: src=files/sources.list/stable dest=/etc/apt/sources.list

    - name: Installing apt-transport-https
      apt: pkg=apt-transport-https state=present

    - name: varnish key
      apt_key: url=https://repo.varnish-cache.org/GPG-key.txt

    - name: add varnish repo
      apt_repository: repo='deb https://repo.varnish-cache.org/debian/ jessie varnish-4.1' state=present

    - name: Installing packages
      apt: pkg={{item}} update_cache=yes state=latest
      with_items:
        - varnish
        - nginx
        - postgresql
