#!/bin/sh

nocaps="[Desktop Entry]
Encoding=UTF-8
Version=0.9.4
Type=Application
Name=nocaps
Comment=nocaps
Exec=setxkbmap -option "ctrl:nocaps"
StartupNotify=false
Terminal=false
Hidden=false
"

term="
[Configuration]
TitleInitial=
ScrollingBar=TERMINAL_SCROLLBAR_NONE
TitleMode=TERMINAL_TITLE_HIDE
MiscAlwaysShowTabs=FALSE
MiscBell=FALSE
MiscBordersDefault=TRUE
MiscCursorBlinks=FALSE
MiscCursorShape=TERMINAL_CURSOR_SHAPE_BLOCK
MiscDefaultGeometry=80x24
MiscInheritGeometry=FALSE
MiscMenubarDefault=FALSE
MiscMouseAutohide=FALSE
MiscToolbarsDefault=FALSE
MiscConfirmClose=TRUE
MiscCycleTabs=TRUE
MiscTabCloseButtons=TRUE
MiscTabCloseMiddleClick=TRUE
MiscTabPosition=GTK_POS_TOP
MiscHighlightUrls=TRUE
ShortcutsNoMnemonics=TRUE
FontName=Monospace 10
ColorPalette1=#1e1e23232020
ColorPalette2=#707050505050
ColorPalette3=#6060b4b48a8a
ColorPalette4=#dfdfafaf8f8f
ColorPalette5=#505060607070
ColorPalette6=#dcdc8c8cc3c3
ColorPalette7=#8c8cd0d0d3d3
ColorPalette8=#dcdcdcdccccc
ColorPalette9=#707090908080
ColorPalette10=#dcdca3a3a3a3
ColorPalette11=#c3c3bfbf9f9f
ColorPalette12=#f0f0dfdfafaf
ColorPalette13=#9494bfbff3f3
ColorPalette14=#ecec9393d3d3
ColorPalette15=#9393e0e0e3e3
ColorPalette16=#ffffffffffff
ColorForeground=#dcdcdcdccccc
ColorBackground=#3f3f3f3f3f3f
ColorCursor=
"


printf "$nocaps" > ~/.config/autostart/nocaps.desktop
mkdir -p ~/.config/Terminal
printf "$term" > ~/.config/Terminal/terminalrc

xfconf-query -c xfce4-panel -p /panels/panel-0/disable-struts -t bool -n -s true
xfconf-query -c xsettings -p /Gtk/KeyThemeName -s Emacs
xfconf-query -c xsettings -p /Xft/Antialias -s 1
xfconf-query -c xsettings -p /Xft/Hinting -s 1
xfconf-query -c xsettings -p /Xft/HintStyle -s hintslight
xfconf-query -c xsettings -p /Xft/RGBA -s rgb
xfconf-query -c xsettings -p /Xft/Lcdfilter -n -t string -s lcddefault
xfconf-query -c xfce4-desktop -p /desktop-icons/style -s 0
