- name: Linking panel config
  copy:
    src: xfce4-panel.xml
    dest: '~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml'
  become: no
  tags: xfce

- name: Running xfce query
  become: no
  script: query
  tags: xfce