#!/bin/sh
xfconf-query -c xsettings -p /Gtk/KeyThemeName -s Emacs
xfconf-query -c xsettings -p /Xft/Antialias -s 1
xfconf-query -c xsettings -p /Xft/Hinting -s 1
xfconf-query -c xsettings -p /Xft/HintStyle -s hintslight
xfconf-query -c xsettings -p /Xft/RGBA -s rgb
xfconf-query -c xsettings -p /Xft/Lcdfilter -n -t string -s lcddefault
xfconf-query --create xfce4-desktop -p /desktop-icons/style -s 0
