- name: add nodesource key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key state=present
  tags: nodejs

- name: add node repo
  apt_repository: repo='deb http://deb.nodesource.com/node_5.x jessie main' state=present
  tags: nodejs

- name: Installing packages
  apt: pkg=nodejs update_cache=yes state=latest
  tags: nodejs
