- name: Installing apt-transport-https
  apt: pkg=apt-transport-https state=presen
  tags: varnish

- name: varnish key
  apt_key: url=https://repo.varnish-cache.org/GPG-key.txt
  tags: varnish

- name: add varnish repo
  apt_repository: repo='deb https://repo.varnish-cache.org/debian/ jessie varnish-4.1' state=present
  tags: varnish

- name: Installing varnish
  apt: varnish state=latest
  tags: varnish
