#! /bin/sh

src="
deb http://kambing.ui.ac.id/debian/ unstable main non-free contrib
deb http://mozilla.debian.net/ experimental iceweasel-aurora
"

sudo sh -c "printf '$src' > /etc/apt/sources.list"
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get autoremove

sudo apt-get install -t experimental iceweasel
sudo apt-get install emacs24 mg git transmission apt-listbugs nginx mpv
sudo apt-get purge vlc gimp

#git clone https://github.com/kusut/.emacs.d.git ~/.emacs.d
