#!/bin/sh
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | sudo python
sudo easy_install pip
sudo pip install virtualenv pep8 pyflakes

bashrc="
export PIP_REQUIRE_VIRTUALENV=true
"

printf "$bashrc" >> ~/.bashrc
. ~/.bashrc
